name: Metrics
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics 1
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

          # Options
          filename: github_metrics_01.svg
          user: dajneem23
          base: header, activity, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          config_twemoji: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2%
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_from: organization
          plugin_notable_indepth: yes
          use_prebuilt_image: yes
          # repositories_skipped:

      - name: Metrics 2
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

          # Options
          filename: github_metrics_02.svg
          user: ansidev
          base: ""
          config_timezone: Asia/Ho_Chi_Minh
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          use_prebuilt_image: yes
          # repositories_skipped:
      - name: Labels
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12

      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          
      - name: Spotify - Random track from playlist
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.music.playlist.spotify.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_playlist: hhttps://open.spotify.com/playlist/4mdzICkf87GYVd1b6ovVIN?si=0da40dc4c5914e47