name: README
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Run workflow when pushing on master/main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_readme:
    name: Update README.md
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Go
        uses: actions/setup-go@v3

      - name: Install markscribe
        run: go install github.com/muesli/markscribe@master

      - name: Fetch latest GitHub statuses
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          GO_PATH=$(go env GOPATH)/bin
          export PATH=${PATH}:${GO_PATH}
          markscribe -write README.md README.md.tpl
          git add README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build: generate GitHub status"
          commit_options: "--signoff"

      - name: Fetch latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://ansidev.xyz/feed.rss,https://leetcode.ansidev.xyz/rss.xml"
          max_post_count: 7
